### PR TITLE
initial support for nnet3

### PR DESCRIPTION
**Pull request by yifan**
support nnet3 decoding. It basically just change all the nnet2 decoding call to nnet3. threaded decoder is not supported though.

### CODE REVIEW

**Comment by alumae** [comment]
Wow, thanks a lot. 
Ideally there would be only one GStreamer plugin, and it would recognize automatically (or via a property) whether nnet2 or nnet3 code should be used. What do you think, would this be difficult to implement? Otherwise we would have a lot of code duplication.

**Comment by yifan** [comment]
You are right, @alumae. It sounds like a better idea. It won't be too much work. I will work on it later today.

**Comment by yifan** [comment]
It is surely doable. The only thing is that some objects in KALDI are not inherited from same super class. Take AmNnetSimple for example, we either keep two pointers in class, and use one of them depending on nnet2 or nnet3 configuration, or we use a 'void *'. Either way, it is not the cleanest way. Let me try it and let's see how it looks like.

**Comment by yifan** [comment]
closed because new pull request is available

**Pull request closed without merging**
